sensor_kit_base_link:
  traffic_light_left_camera/camera_link:
    x: 1.80
    y: 0.25
    z: 1.65
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera_front:
    x: 1.80
    y: 0.25
    z: 1.65
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera_frontal:
    x: 2.3
    y: -0.3
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera_rear:
    x: -2.3
    y: 0.0
    z: 1.0
    roll: 0.0
    pitch: 0.0
    yaw: 3.14159265
  camera_center:
    x: 1.5
    y: 0.0
    z: 2.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera_right:
    x: 1.45
    y: -1.0
    z: 1.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera_left:
    x: 1.45
    y: 1.0
    z: 1.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lidar_front:
    x: 1.3
    y: 0.0
    z: 2.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gnss_link:
    x: 0.2
    y: 0.2
    z: 2.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: -0.2
    y: -0.2
    z: 2.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  radar_front_center:
    x: 2.1
    y: 0.3
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  radar_front_right:
    x: 2.1
    y: -0.8
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  radar_front_left:
    x: 2.1
    y: 0.8
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  radar_rear_right:
    x: -2.3
    y: -0.8
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 3.14159265359
  radar_rear_left:
    x: -2.3
    y: 0.8
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 3.14159265359    
